version: "3"

services:
  pg:
    image: postgres:latest
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=prisma
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "./db/data:/var/lib/postgres/data"
      - "./db/init:/docker-entrypoint-initdb.d"

